# runtime: python310  
# env: standard  

# # entrypoint: gunicorn -b :$PORT HandmadeBidSystem.HandmadeBidSystem.wsgi :application
# entrypoint: python3 main.py

# env_variables:
#   APPENGINE_URL: https://db-123456.uc.r.appspot.com
#   DJANGO_SETTINGS_MODULE: 'HandmadeBidSystem.settings'



# automatic_scaling:
#   min_instances: 1  
#   max_instances: 10  
#   target_cpu_utilization: 0.6  
#   target_throughput_utilization: 0.75 
#   max_concurrent_requests: 80  




# handlers:
# - url: /static
#   static_dir: static/
# - url: /.*
#   script: auto



# flex env 
runtime: python
env: flex  

entrypoint: gunicorn -b :$PORT HandmadeBidSystem.wsgi:application 

env_variables:
  APPENGINE_URL: https://db-123456.uc.r.appspot.com
  DJANGO_SETTINGS_MODULE: 'HandmadeBidSystem.settings'

runtime_config:  
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.6

resources:  
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
