-- Drop Views
DROP VIEW IF EXISTS ORDERSVIEW;
DROP VIEW IF EXISTS AVGSELLPRICE;
DROP VIEW IF EXISTS BESTSELL;

-- Drop Triggers
DROP TRIGGER IF EXISTS rate_update;
DROP TRIGGER IF EXISTS check_quantity;

-- Drop Tables with no dependencies
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS PAYMENT;

-- Drop Tables with dependent records that need to be cleaned up first
DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS BIDDING;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PICTURES;

-- These might have dependencies and should be carefully ordered
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ADDRESS;

-- Drop Intermediate Tables
DROP TABLE IF EXISTS GENERATES;
DROP TABLE IF EXISTS NORMALUSER;
DROP TABLE IF EXISTS ADMIN_TOKEN;


-- Finally, drop the base and root tables
DROP TABLE IF EXISTS ADMINUSER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS BASEUSER;

-- Drop Procedures
DROP PROCEDURE IF EXISTS GetReviews;
DROP PROCEDURE IF EXISTS GetHistoryOrders;
DROP PROCEDURE IF EXISTS GetProducts;
