# Generated by Django 5.0.2 on 2024-03-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ADMINUSER',
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(db_column='Email', max_length=254, unique=True, verbose_name='email address')),
                ('Fname', models.CharField(db_column='Fname', max_length=25)),
                ('Lname', models.CharField(db_column='Lname', max_length=25)),
                ('Username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('DefaultAddressID', models.IntegerField(blank=True, db_column='DefaultAddressID', null=True)),
                ('Phone', models.CharField(blank=True, db_column='Phone', max_length=30, null=True)),
                ('Rate', models.DecimalField(blank=True, db_column='Rate', decimal_places=1, max_digits=3, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ManageID', models.ForeignKey(blank=True, db_column='ManageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='handmadeBid.adminuser')),
            ],
            options={
                'db_table': 'NORMALUSER',
            },
        ),
    ]
