# Generated by Django 5.0.2 on 2024-04-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeBid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='Street', max_length=255)),
                ('streeoptional', models.CharField(blank=True, db_column='StreeOptional', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='Zipcode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'ADDRESS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('biddingid', models.AutoField(primary_key=True, serialize=False)),
                ('bidprice', models.DecimalField(db_column='BidPrice', decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('biddate', models.DateField(db_column='BidDate')),
                ('activedays', models.IntegerField(blank=True, db_column='ActiveDays', null=True)),
                ('status', models.CharField(db_column='Status', max_length=8)),
            ],
            options={
                'db_table': 'BIDDING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.IntegerField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, db_column='CName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CATEGORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(blank=True, db_column='OrderDate', null=True)),
                ('orderstatus', models.CharField(db_column='OrderStatus', max_length=10)),
            ],
            options={
                'db_table': 'ORDERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField(db_column='ProductID', null=True)),
                ('picture', models.ImageField(upload_to='photos')),
            ],
            options={
                'db_table': 'PICTURES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('startprice', models.DecimalField(blank=True, db_column='StartPrice', decimal_places=2, max_digits=7, null=True)),
                ('pictureid', models.IntegerField(db_column='PictureID')),
                ('postdate', models.DateField(blank=True, db_column='PostDate', null=True)),
                ('status', models.CharField(db_column='Status', max_length=8)),
                ('inventory', models.IntegerField(db_column='Inventory')),
            ],
            options={
                'db_table': 'PRODUCTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='handmadeBid.orders')),
                ('paymentstatus', models.CharField(db_column='PaymentStatus', max_length=9)),
                ('paymentmethod', models.CharField(db_column='PaymentMethod', max_length=17)),
            ],
            options={
                'db_table': 'PAYMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=1000)),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('AdminReceiveID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_received_messages', to='handmadeBid.adminuser')),
                ('AdminSenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_send_message', to='handmadeBid.adminuser')),
                ('OrderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handmadeBid.orders')),
                ('ProductID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handmadeBid.products')),
                ('ReceiverID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_received_messages', to='handmadeBid.normaluser')),
                ('SenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_message', to='handmadeBid.normaluser')),
            ],
            options={
                'db_table': 'MESSAGES',
            },
        ),
    ]
