# Generated by Django 5.0.2 on 2024-03-31 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeBid', '0002_alter_normaluser_manageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='ManageID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handmadeBid.adminuser'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='UserID',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
