# Generated by Django 5.0.2 on 2024-03-31 00:25

from django.db import migrations
from django.contrib.auth.hashers import make_password



def create_adminuser(apps, schema_editor):
    AdminUser = apps.get_model('handmadeBid', 'AdminUser')
    hashed_password = make_password('adminpassword')
    admin_user = AdminUser(
        Fname='Admin',
        Lname='AM',
        Password=hashed_password
    )
    admin_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeBid', '0003_alter_normaluser_manageid_alter_normaluser_userid'),
    ]

    operations = [
        migrations.RunPython(create_adminuser),
    ]
