# Generated by Django 5.0.3 on 2024-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeBid', '0004_auto_20240331_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='UserID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
