# Generated by Django 5.0.3 on 2024-04-01 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmadeBid', '0005_alter_normaluser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='ManageID',
            field=models.ForeignKey(blank=True, db_column='ManageID', null=True, on_delete=django.db.models.deletion.CASCADE, to='handmadeBid.adminuser'),
        ),
    ]
